### ISSUE TITLE
Session serializer crashes

### ISSUE THREAD

**Issue by ricksanchez** [msgpack/msgpack-php#116]
If there is invalid data in the session:
\xC0\xBEsomething
for example, the php process crashes.

It should just return empty (I guess)

**Comment by laruence** [comment]
could you paste the backtrace of coredump out here?

**Comment by udarkness** [comment]
Sure, additional notes: php7.0 with phalcon, xdebug installed (not active on that request)

The msgpack extension is 2.0.2 
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1a66a40c2b in ps_srlzr_decode_msgpack ()
   from /usr/lib/php/20151012/msgpack.so
(gdb) bt
#0  0x00007f1a66a40c2b in ps_srlzr_decode_msgpack ()
   from /usr/lib/php/20151012/msgpack.so
#1  0x000055d5c4d8169f in ?? ()
#2  0x000055d5c4d84d86 in ?? ()
#3  0x000055d5c4d856ed in php_session_start ()
#4  0x000055d5c4d868dd in ?? ()
#5  0x00007f1a68db4f8d in xdebug_execute_internal (
    current_execute_data=0x7f1a6ac15a00, return_value=0x7ffe56528e60)
    at /home/ricardo/Documents/xdebug-2.4.0/xdebug.c:2037
#6  0x00007f1a612de46c in zephir_call_user_function ()
   from /usr/lib/php/20151012/phalcon.so
#7  0x00007f1a612e2f51 in zephir_call_func_aparams ()
   from /usr/lib/php/20151012/phalcon.so
#8  0x00007f1a6133cf22 in zim_Phalcon_Session_Adapter_start ()
   from /usr/lib/php/20151012/phalcon.so
#9  0x00007f1a68db4f8d in xdebug_execute_internal (
    current_execute_data=0x7f1a6ac159a0, return_value=0x7f1a6ac15980)
    at /home/ricardo/Documents/xdebug-2.4.0/xdebug.c:2037
#10 0x000055d5c4f0d630 in ?? ()
#11 0x000055d5c4ec87bb in execute_ex ()
#12 0x00007f1a68db446f in xdebug_execute_ex (execute_data=0x7f1a6ac158f0)
    at /home/ricardo/Documents/xdebug-2.4.0/xdebug.c:1890
#13 0x000055d5c4e78bc3 in zend_call_function ()
```
