### ISSUE TITLE
Segfault on session php 7

### ISSUE THREAD

**Issue by austinh** [msgpack/msgpack-php#66]
Hello when using ```session.serialize_handler = "msgpack" ``` I get a segfault error.

I am using PHP 7.0RC5 with php7-fpm and nginx with msgpack-php branch php7. Debian 7.9

This is the core dump.

```
warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php-fpm: pool www                                                             '.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fbd06d6d60b in ps_srlzr_decode_msgpack (
    val=0x7fbd088777f8 "symfony/user/sfUser/lastRequest|i:1445232500;symfony/user/sfUser/authenticated|b:0;symfony/user/sfUser/credentials|a:0:{}symfony/user/sfUser/attributes|a:0:{}symfony/user/sfUser/culture|s:2:\"en\";", vallen=195) at /root/msgpack-php/msgpack.c:178
#1  0x000000000069a8ff in php_session_decode (data=<optimized out>) at /php-7-debian/php-src/ext/session/session.c:237
#2  0x000000000069d9ae in php_session_initialize () at /php-7-debian/php-src/ext/session/session.c:541
#3  0x000000000069e1cd in php_session_start () at /php-7-debian/php-src/ext/session/session.c:1623
#4  0x000000000069ead7 in zif_session_start (execute_data=<optimized out>, return_value=0x7fbd08815570) at /php-7-debian/php-src/ext/session/session.c:2301
#5  0x0000000000869db2 in ZEND_DO_ICALL_SPEC_HANDLER (execute_data=0x7fbd08815480) at /php-7-debian/php-src/Zend/zend_vm_execute.h:586
#6  0x000000000085aaa0 in execute_ex (ex=<optimized out>) at /php-7-debian/php-src/Zend/zend_vm_execute.h:417
#7  0x00000000008aaf37 in zend_execute (op_array=op_array@entry=0x7fbd08877000, return_value=return_value@entry=0x0) at /php-7-debian/php-src/Zend/zend_vm_execute.h:458
#8  0x000000000081e094 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /php-7-debian/php-src/Zend/zend.c:1428
#9  0x00000000007c00e0 in php_execute_script (primary_file=primary_file@entry=0x7fffdd0052c0) at /php-7-debian/php-src/main/main.c:2471
#10 0x000000000044739e in main (argc=<optimized out>, argv=<optimized out>) at /php-7-debian/php-src/sapi/fpm/fpm/fpm_main.c:1944

```

**Comment by Sean-Der** [comment]
Hey @austinh !

Glad it works for you now, what ended up being the issue?

**Comment by austinh** [comment]
I am not entirely sure. I reinstalled from source and restarted php-fpm and it seemed to work.
