### ISSUE TITLE
PHP7 msgpack_unserialize_map_item illegal key type

### ISSUE THREAD

**Issue by caleblloyd** [msgpack/msgpack-php#75]
Hit this when unserilaizing an item.  PHP-FPM throws warning "[msgpack (msgpack_unserialize_map_item) illegal key type".  PHP CLI segfaults, backtrace is here:

```
#0  i_zval_ptr_dtor (zval_ptr=zval_ptr@entry=0x7fe948a8af70)
    at /usr/local/php7/src/php-src/Zend/zend_variables.h:57
57          if (!Z_DELREF_P(zval_ptr)) {
Traceback (most recent call last):
File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  i_zval_ptr_dtor (zval_ptr=zval_ptr@entry=0x7fe948a8af70)
    at /usr/local/php7/src/php-src/Zend/zend_variables.h:57
#1  _zval_ptr_dtor (zval_ptr=zval_ptr@entry=0x7fe948a8af70)
    at /usr/local/php7/src/php-src/Zend/zend_execute_API.c:527
#2  0x00007fe9485c2e70 in msgpack_unserialize_var_destroy (
    var_hashx=var_hashx@entry=0x7ffcd8c0c3c0, err=err@entry=0 '\000')
    at /usr/local/php7/src/msgpack-php/msgpack_unpack.c:301
#3  0x00007fe9485be633 in php_msgpack_unserialize (
    return_value=return_value@entry=0x7fe948a130d0, 
    str=0x7fe948a85018 "\222\201\257authAssignments\215\265company_administrator\210\300\257CAuthAssignment\266", str_len=4315) at /usr/local/php7/src/msgpack-php/msgpack.c:238
#4  0x00007fe9485be808 in zif_msgpack_unserialize (execute_data=<optimized out>, 
    return_value=0x7fe948a130d0) at /usr/local/php7/src/msgpack-php/msgpack.c:285
#5  0x000000000089698d in ZEND_DO_ICALL_SPEC_HANDLER ()
    at /usr/local/php7/src/php-src/Zend/zend_vm_execute.h:586
#6  0x0000000000888edb in execute_ex (ex=<optimized out>)
    at /usr/local/php7/src/php-src/Zend/zend_vm_execute.h:414
#7  0x00000000008d1aa7 in zend_execute (op_array=0x7fe948a7c000, op_array@entry=0x7fe93da38990, 
    return_value=return_value@entry=0x7fe948a13030)
    at /usr/local/php7/src/php-src/Zend/zend_vm_execute.h:458
#8  0x000000000084d9b4 in zend_execute_scripts (type=type@entry=8, retval=0x7fe948a13030, 
    retval@entry=0x0, file_count=file_count@entry=3)
---Type <return> to continue, or q <return> to quit---
    at /usr/local/php7/src/php-src/Zend/zend.c:1428
#9  0x00000000007f1da8 in php_execute_script (primary_file=primary_file@entry=0x7ffcd8c18900)
    at /usr/local/php7/src/php-src/main/main.c:2471
#10 0x00000000008d3673 in do_cli (argc=2, argv=0x1500770)
    at /usr/local/php7/src/php-src/sapi/cli/php_cli.c:974
#11 0x000000000044cc50 in main (argc=2, argv=0x1500770)
    at /usr/local/php7/src/php-src/sapi/cli/php_cli.c:1345
```

I noticed that in the function in question, msgpack_unserialize_var_destroy, the Master branch has some code commented out:

https://github.com/msgpack/msgpack-php/blob/master/msgpack_unpack.c#L346

But on the PHP7 branch that code is not commented out:

https://github.com/msgpack/msgpack-php/blob/php7/msgpack_unpack.c#L288

I'd prefer to not post the packed code on GitHub, if you need it to debug though please email me caleblloyd on gmail.

**Comment by caleblloyd** [comment]
Just tried commenting out those 2 lines of code in the PHP7 branch and still hit this issue.  I think something else is going on.

**Comment by Sean-Der** [comment]
@caleblloyd you are hitting lots of good stuff! Sorry about all the headaches :/

is mgpack-php packing this data, or is it coming from somewhere else? Would you mind sending the data to sean@siobud.com

**Comment by caleblloyd** [comment]
@Sean-Der msgpack-php is packing the data (same package, php-7 branch on php 7.0.0).  I can unpack the data just fine in the php 5.6 version, seems the problem is in the unpacking in php 7.

just emailed the data for the recreate, segfault happens in command line now so it's an easier recreate.  no problem, glad to help vet out the issues!

**Comment by caleblloyd** [comment]
@Sean-Der any ideas what the problem might be?
